# The ID of the data source is the name of this file. Should be short, consists of one or two words. No space and special characters. Hyphen ("_") is allowed. The ID is for the program identify the data source.

# Data source name. Should be clear, meaningful, and human readable.
data_source_name = 'US COVID-19 data by New York Times'


# provide a brief description (1 line) of the data source to inform AI whether need to use this data source.
# Need to contain critical information such as extent and period.
brief_description = '''
US COVID-19 data by New York Times. Cumulative counts of COVID-19 cases and deaths in the United States, at the state and county level, over time from 2020-01-21 to 2023-03-23.
'''



# Put the technical requirements or details for the data source. One line for a requirement. No need to number them.
handbook = '''
The COVID-19 cumulative death and case data can be accessed via: https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties-{year}.csv, year can be 2021, 2022,and 2023.
The CSV columns are: `date,county,state,fips,cases,deaths`, the data line can be: `2020-01-21,Washington,53,1,0`. Note that the data-type of `fips` column is string, while the `case` and `deaths` are integer. You need to store the data type correctly.
Put your reply into a Python code block. Explanation or conversation can be Python comments at the begining of the code block(enclosed by ```python and ```).
The download code is only in a function named 'download_data()'. The last line is to execute this function.
'''

